Card View added
agiledev-students-spring-2023/final-project-stoopit-project pull request #30
Opened 2023-03-03 17:49 UTC by szcharlesji

#27

2023-03-03 18:01 UTC, 163dgm commented on front-end/src/containers/Card/Card.jsx
> +		<div className="card card-compact h-1/5 bg-base-100 shadow-xl">
You can't use Tailwind (the classes like h-1/5 bg-base-100) You need to comvert this to css. Look at Tailwind docs to see what converts to what.

For example, in https://tailwindcss.com/docs/height, `h-1/5` is equal to `height: 20%;`

2023-03-03 18:09 UTC, 163dgm commented on front-end/src/containers/Card/Card.jsx
> +				<img src={props.img} alt="img" />
`alt` needs to have meaningful text as to what the image is, this is shown when the image cannot be loaded so something like "img" isn't good, I'd say put `alt="stoop"`

2023-03-03 18:12 UTC, 163dgm commented on front-end/src/containers/Card/Card.jsx
> +					<svg
Can you leave a comment like I said about icons, so we know what this is. Like
`{ /* Heroicons: solid/icon-name-here */ }`

2023-03-03 18:14 UTC, 163dgm commented on front-end/src/containers/Card/Card.jsx
> +import PropTypes from 'prop-types'
Actually, its nice to have you can keep this

2023-03-03 18:15 UTC, 163dgm requested changes
You need to convert your styles in the component to CSS, we can't use Tailwind

2023-03-03 19:56 UTC, KaiElwood commented on front-end/src/containers/Card/Card.jsx
> +						<svg
Can you please update this to remove the icon from the component? Instead, create a folder for icons and import the icon into the project. Let me know if you have questions

2023-03-03 20:01 UTC, KaiElwood commented on front-end/src/containers/Card/StoopList.jsx
> +	const stoopsList = Stoops.map((stoop) => {
please move this logic into the return below rather than making a variable called stoopsList

2023-03-03 20:01 UTC, KaiElwood commented on front-end/src/containers/Card/StoopList.jsx
> +			<Card
Description needed for each card. Also, we don't have a date field which actually might be an issue...

2023-03-03 21:31 UTC, 163dgm commented on front-end/src/containers/Card/StoopList.jsx
> +	const stoopsList = Stoops.map((stoop) => {
this is valid React and shown in the docs, lowkey have no issue with this, it's kinda clean

2023-03-03 23:57 UTC, szcharlesji reviewed
resolved issues posted

2023-03-04 00:28 UTC, 163dgm approved these changes
Nice first PR!

2023-03-04 00:29 UTC, merged